Repository brain-tec/account-analytic, pull requests merged in 2019-06, with the labels that each got.

#177 Syncing from upstream OCA/account-analytic (6.1)
  account_analytic_project/__openerp__.py
  analytic_secondaxis/__openerp__.py
  analytic_secondaxis_timesheet/__openerp__.py
Labels: 6.1

#178 Syncing from upstream OCA/account-analytic (7.0)
  account_analytic_unique_reference/__openerp__.py
  hr_expense_analytic_plans/__openerp__.py
Labels: 7.0

#179 Syncing from upstream OCA/account-analytic (6.1)
  analytic_multicurrency/__openerp__.py
  analytic_secondaxis_multicurrency/__openerp__.py
  analytic_secondaxis_project/__openerp__.py
Labels: 6.1

#180 Syncing from upstream OCA/account-analytic (8.0)
  analytic_partner/__openerp__.py
  analytic_partner_hr_timesheet/__openerp__.py
Labels: 8.0

#181 Syncing from upstream OCA/account-analytic (12.0)
  account_analytic_required/README.rst
  account_analytic_required/__init__.py
  account_analytic_required/__manifest__.py
  account_analytic_required/i18n/account_analytic_required.pot
  account_analytic_required/i18n/ar.po
  account_analytic_required/i18n/ca.po
  account_analytic_required/i18n/de.po
  account_analytic_required/i18n/es.po
  account_analytic_required/i18n/es_CO.po
  account_analytic_required/i18n/fr.po
  account_analytic_required/i18n/hr_HR.po
  account_analytic_required/i18n/nl.po
  account_analytic_required/i18n/pt_BR.po
  account_analytic_required/models/__init__.py
  account_analytic_required/models/account.py
  account_analytic_required/readme/CONFIGURE.rst
  account_analytic_required/readme/CONTRIBUTORS.rst
  account_analytic_required/readme/DESCRIPTION.rst
  account_analytic_required/readme/USAGE.rst
  account_analytic_required/static/description/icon.png
  account_analytic_required/static/description/index.html
  account_analytic_required/tests/__init__.py
  account_analytic_required/tests/test_account_analytic_required.py
  account_analytic_required/views/account.xml
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_analytic_required/odoo/addons/account_analytic_required
  setup/account_analytic_required/setup.py
Labels: 12.0

#182 [t114688] Integrated into our branch the pull #223 from OCA, which ports the module stock_analytic.
  stock_analytic/README.rst
  stock_analytic/__init__.py
  stock_analytic/__manifest__.py
  stock_analytic/i18n/ca.po
  stock_analytic/i18n/cs_CZ.po
  stock_analytic/i18n/de.po
  stock_analytic/i18n/el_GR.po
  stock_analytic/i18n/es.po
  stock_analytic/i18n/es_EC.po
  stock_analytic/i18n/es_MX.po
  stock_analytic/i18n/fi.po
  stock_analytic/i18n/fr.po
  stock_analytic/i18n/gl.po
  stock_analytic/i18n/gu_IN.po
  stock_analytic/i18n/hi_IN.po
  stock_analytic/i18n/hr.po
  stock_analytic/i18n/hr_HR.po
  stock_analytic/i18n/hu.po
  stock_analytic/i18n/it.po
  stock_analytic/i18n/nl.po
  stock_analytic/i18n/pt.po
  stock_analytic/i18n/pt_BR.po
  stock_analytic/i18n/pt_PT.po
  stock_analytic/i18n/ro.po
  stock_analytic/i18n/sk_SK.po
  stock_analytic/i18n/sl.po
  stock_analytic/i18n/stock_analytic.pot
  stock_analytic/i18n/tr.po
  stock_analytic/i18n/tr_TR.po
  stock_analytic/i18n/vi_VN.po
  stock_analytic/i18n/zh_CN.po
  stock_analytic/models/__init__.py
  stock_analytic/models/stock.py
  stock_analytic/static/description/icon.png
  stock_analytic/tests/__init__.py
  stock_analytic/tests/test_stock_picking.py
  stock_analytic/views/stock_move_views.xml
Labels: 12.0.project_mi_465

#183 [t114688] Updated the tests of the module stock_analytic.
  stock_analytic/tests/test_stock_picking.py
Labels: 12.0.project_mi_465

#184 [t114688] Migration of stock_inventory_analytic from 11.0 to 12.0.
  stock_inventory_analytic/README.rst
  stock_inventory_analytic/__init__.py
  stock_inventory_analytic/__manifest__.py
  stock_inventory_analytic/i18n/stock_inventory_analytic.pot
  stock_inventory_analytic/models/__init__.py
  stock_inventory_analytic/models/stock_inventory_line.py
  stock_inventory_analytic/models/stock_move.py
  stock_inventory_analytic/readme/CONTRIBUTORS.rst
  stock_inventory_analytic/readme/DESCRIPTION.rst
  stock_inventory_analytic/static/description/icon.png
  stock_inventory_analytic/static/description/index.html
  stock_inventory_analytic/tests/__init__.py
  stock_inventory_analytic/tests/test_stock_inventory_analytic.py
  stock_inventory_analytic/views/stock_inventory_line_view.xml
  stock_inventory_analytic/wizard/__init__.py
  stock_inventory_analytic/wizard/stock_change_product_qty.py
  stock_inventory_analytic/wizard/stock_product_change_qty.xml
Labels: 12.0.project_mi_465

#185 Syncing from upstream OCA/account-analytic (12.0)
  account_analytic_required/i18n/ar.po
  account_analytic_required/i18n/ca.po
  account_analytic_required/i18n/de.po
  account_analytic_required/i18n/es.po
  account_analytic_required/i18n/es_CO.po
  account_analytic_required/i18n/fr.po
  account_analytic_required/i18n/hr_HR.po
  account_analytic_required/i18n/nl.po
  account_analytic_required/i18n/pt_BR.po
  product_analytic/i18n/ar.po
  product_analytic/i18n/bs.po
  product_analytic/i18n/ca.po
  product_analytic/i18n/cs.po
  product_analytic/i18n/cs_CZ.po
  product_analytic/i18n/de.po
  product_analytic/i18n/en_GB.po
  product_analytic/i18n/es.po
  product_analytic/i18n/es_CO.po
  product_analytic/i18n/es_CR.po
  product_analytic/i18n/es_EC.po
  product_analytic/i18n/es_MX.po
  product_analytic/i18n/et.po
  product_analytic/i18n/fi.po
  product_analytic/i18n/fr.po
  product_analytic/i18n/fr_CH.po
  product_analytic/i18n/hr.po
  product_analytic/i18n/hr_HR.po
  product_analytic/i18n/hu.po
  product_analytic/i18n/it.po
  product_analytic/i18n/ja.po
  product_analytic/i18n/lt.po
  product_analytic/i18n/mk.po
  product_analytic/i18n/mn.po
  product_analytic/i18n/nb.po
  product_analytic/i18n/nl.po
  product_analytic/i18n/nl_BE.po
  product_analytic/i18n/nl_NL.po
  product_analytic/i18n/pt.po
  product_analytic/i18n/pt_BR.po
  product_analytic/i18n/pt_PT.po
  product_analytic/i18n/ro.po
  product_analytic/i18n/ru.po
  product_analytic/i18n/sl.po
  product_analytic/i18n/sv.po
  product_analytic/i18n/tr.po
  product_analytic/i18n/tr_TR.po
  product_analytic/i18n/zh_CN.po
  product_analytic/i18n/zh_TW.po
Labels: 12.0

#187 Syncing from upstream OCA/account-analytic (12.0)
  analytic_tag_dimension/i18n/ar.po
  analytic_tag_dimension/i18n/bs.po
  analytic_tag_dimension/i18n/ca.po
  analytic_tag_dimension/i18n/cs.po
  analytic_tag_dimension/i18n/cs_CZ.po
  analytic_tag_dimension/i18n/de.po
  analytic_tag_dimension/i18n/en_GB.po
  analytic_tag_dimension/i18n/es.po
  analytic_tag_dimension/i18n/es_CO.po
  analytic_tag_dimension/i18n/es_CR.po
  analytic_tag_dimension/i18n/es_EC.po
  analytic_tag_dimension/i18n/es_MX.po
  analytic_tag_dimension/i18n/et.po
  analytic_tag_dimension/i18n/fi.po
  analytic_tag_dimension/i18n/fr.po
  analytic_tag_dimension/i18n/fr_CH.po
  analytic_tag_dimension/i18n/hr.po
  analytic_tag_dimension/i18n/hr_HR.po
  analytic_tag_dimension/i18n/hu.po
  analytic_tag_dimension/i18n/it.po
  analytic_tag_dimension/i18n/ja.po
  analytic_tag_dimension/i18n/lt.po
  analytic_tag_dimension/i18n/mk.po
  analytic_tag_dimension/i18n/mn.po
  analytic_tag_dimension/i18n/nb.po
  analytic_tag_dimension/i18n/nl.po
  analytic_tag_dimension/i18n/nl_BE.po
  analytic_tag_dimension/i18n/nl_NL.po
  analytic_tag_dimension/i18n/pt.po
  analytic_tag_dimension/i18n/pt_BR.po
  analytic_tag_dimension/i18n/pt_PT.po
  analytic_tag_dimension/i18n/ro.po
  analytic_tag_dimension/i18n/ru.po
  analytic_tag_dimension/i18n/sl.po
  analytic_tag_dimension/i18n/sv.po
  analytic_tag_dimension/i18n/tr.po
  analytic_tag_dimension/i18n/tr_TR.po
  analytic_tag_dimension/i18n/zh_CN.po
  analytic_tag_dimension/i18n/zh_TW.po
Labels: 12.0
