Repository brain-tec/account-analytic, pull requests merged in 2020-11, with the labels that each got.

#306 Syncing from upstream OCA/account-analytic (12.0)
  analytic_tag_dimension/README.rst
  analytic_tag_dimension/__init__.py
  analytic_tag_dimension/__manifest__.py
  analytic_tag_dimension/hooks.py
  analytic_tag_dimension/i18n/analytic_tag_dimension.pot
  analytic_tag_dimension/i18n/ar.po
  analytic_tag_dimension/i18n/bs.po
  analytic_tag_dimension/i18n/ca.po
  analytic_tag_dimension/i18n/cs.po
  analytic_tag_dimension/i18n/cs_CZ.po
  analytic_tag_dimension/i18n/de.po
  analytic_tag_dimension/i18n/en_GB.po
  analytic_tag_dimension/i18n/es.po
  analytic_tag_dimension/i18n/es_CO.po
  analytic_tag_dimension/i18n/es_CR.po
  analytic_tag_dimension/i18n/es_EC.po
  analytic_tag_dimension/i18n/es_MX.po
  analytic_tag_dimension/i18n/et.po
  analytic_tag_dimension/i18n/fi.po
  analytic_tag_dimension/i18n/fr.po
  analytic_tag_dimension/i18n/fr_CH.po
  analytic_tag_dimension/i18n/hr.po
  analytic_tag_dimension/i18n/hr_HR.po
  analytic_tag_dimension/i18n/hu.po
  analytic_tag_dimension/i18n/it.po
  analytic_tag_dimension/i18n/ja.po
  analytic_tag_dimension/i18n/lt.po
  analytic_tag_dimension/i18n/mk.po
  analytic_tag_dimension/i18n/mn.po
  analytic_tag_dimension/i18n/nb.po
  analytic_tag_dimension/i18n/nl.po
  analytic_tag_dimension/i18n/nl_BE.po
  analytic_tag_dimension/i18n/nl_NL.po
  analytic_tag_dimension/i18n/pt.po
  analytic_tag_dimension/i18n/pt_BR.po
  analytic_tag_dimension/i18n/pt_PT.po
  analytic_tag_dimension/i18n/ro.po
  analytic_tag_dimension/i18n/ru.po
  analytic_tag_dimension/i18n/sl.po
  analytic_tag_dimension/i18n/sv.po
  analytic_tag_dimension/i18n/tr.po
  analytic_tag_dimension/i18n/tr_TR.po
  analytic_tag_dimension/i18n/zh_CN.po
  analytic_tag_dimension/i18n/zh_TW.po
  analytic_tag_dimension/models/__init__.py
  analytic_tag_dimension/models/account_analytic_dimension.py
  analytic_tag_dimension/models/account_analytic_line.py
  analytic_tag_dimension/models/account_analytic_tag.py
  analytic_tag_dimension/models/account_invoice_line.py
  analytic_tag_dimension/models/account_move_line.py
  analytic_tag_dimension/models/analytic.py
  analytic_tag_dimension/models/analytic_dimension_line.py
  analytic_tag_dimension/static/description/index.html
  analytic_tag_dimension/tests/test_analytic_dimension.py
  analytic_tag_dimension_enhanced/__manifest__.py
  analytic_tag_dimension_enhanced/tests/test_analytic_dimension.py
Labels: 12.0

#307 Syncing from upstream OCA/account-analytic (13.0)
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: 13.0

#308 Syncing from upstream OCA/account-analytic (14.0)
  .copier-answers.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
Labels: 14.0

#309 Syncing from upstream OCA/account-analytic (13.0)
  analytic_tag_dimension/README.rst
  analytic_tag_dimension/__init__.py
  analytic_tag_dimension/__manifest__.py
  analytic_tag_dimension/hooks.py
  analytic_tag_dimension/i18n/analytic_tag_dimension.pot
  analytic_tag_dimension/i18n/ar.po
  analytic_tag_dimension/i18n/bs.po
  analytic_tag_dimension/i18n/ca.po
  analytic_tag_dimension/i18n/cs.po
  analytic_tag_dimension/i18n/cs_CZ.po
  analytic_tag_dimension/i18n/de.po
  analytic_tag_dimension/i18n/en_GB.po
  analytic_tag_dimension/i18n/es.po
  analytic_tag_dimension/i18n/es_CO.po
  analytic_tag_dimension/i18n/es_CR.po
  analytic_tag_dimension/i18n/es_EC.po
  analytic_tag_dimension/i18n/es_MX.po
  analytic_tag_dimension/i18n/et.po
  analytic_tag_dimension/i18n/fi.po
  analytic_tag_dimension/i18n/fr.po
  analytic_tag_dimension/i18n/fr_CH.po
  analytic_tag_dimension/i18n/hr.po
  analytic_tag_dimension/i18n/hr_HR.po
  analytic_tag_dimension/i18n/hu.po
  analytic_tag_dimension/i18n/it.po
  analytic_tag_dimension/i18n/ja.po
  analytic_tag_dimension/i18n/lt.po
  analytic_tag_dimension/i18n/mk.po
  analytic_tag_dimension/i18n/mn.po
  analytic_tag_dimension/i18n/nb.po
  analytic_tag_dimension/i18n/nl.po
  analytic_tag_dimension/i18n/nl_BE.po
  analytic_tag_dimension/i18n/nl_NL.po
  analytic_tag_dimension/i18n/pt.po
  analytic_tag_dimension/i18n/pt_BR.po
  analytic_tag_dimension/i18n/pt_PT.po
  analytic_tag_dimension/i18n/ro.po
  analytic_tag_dimension/i18n/ru.po
  analytic_tag_dimension/i18n/sl.po
  analytic_tag_dimension/i18n/sv.po
  analytic_tag_dimension/i18n/tr.po
  analytic_tag_dimension/i18n/tr_TR.po
  analytic_tag_dimension/i18n/zh_CN.po
  analytic_tag_dimension/i18n/zh_TW.po
  analytic_tag_dimension/models/__init__.py
  analytic_tag_dimension/models/account_analytic_dimension.py
  analytic_tag_dimension/models/account_analytic_line.py
  analytic_tag_dimension/models/account_analytic_tag.py
  analytic_tag_dimension/models/account_move_line.py
  analytic_tag_dimension/models/analytic.py
  analytic_tag_dimension/models/analytic_dimension_line.py
  analytic_tag_dimension/static/description/index.html
  analytic_tag_dimension/tests/test_analytic_dimension.py
Labels: 13.0

#310 Syncing from upstream OCA/account-analytic (13.0)
  .pre-commit-config.yaml
Labels: 13.0

#311 Syncing from upstream OCA/account-analytic (12.0)
  account_analytic_parent/README.rst
  account_analytic_parent/__manifest__.py
  account_analytic_parent/readme/CONTRIBUTORS.rst
  account_analytic_parent/static/description/index.html
  account_analytic_sequence/README.rst
  account_analytic_sequence/readme/CONTRIBUTORS.rst
  account_analytic_sequence/static/description/index.html
Labels: 12.0

#312 Syncing from upstream OCA/account-analytic (13.0)
  account_analytic_parent/README.rst
  account_analytic_parent/__manifest__.py
  account_analytic_parent/readme/CONTRIBUTORS.rst
  account_analytic_parent/static/description/index.html
Labels: 13.0

#313 Merge 13.0 into 13.0.project_TE_576
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  account_analytic_parent/README.rst
  account_analytic_parent/__manifest__.py
  account_analytic_parent/readme/CONTRIBUTORS.rst
  account_analytic_parent/static/description/index.html
  analytic_tag_dimension/README.rst
  analytic_tag_dimension/__init__.py
  analytic_tag_dimension/__manifest__.py
  analytic_tag_dimension/hooks.py
  analytic_tag_dimension/i18n/analytic_tag_dimension.pot
  analytic_tag_dimension/i18n/ar.po
  analytic_tag_dimension/i18n/bs.po
  analytic_tag_dimension/i18n/ca.po
  analytic_tag_dimension/i18n/cs.po
  analytic_tag_dimension/i18n/cs_CZ.po
  analytic_tag_dimension/i18n/de.po
  analytic_tag_dimension/i18n/en_GB.po
  analytic_tag_dimension/i18n/es.po
  analytic_tag_dimension/i18n/es_CO.po
  analytic_tag_dimension/i18n/es_CR.po
  analytic_tag_dimension/i18n/es_EC.po
  analytic_tag_dimension/i18n/es_MX.po
  analytic_tag_dimension/i18n/et.po
  analytic_tag_dimension/i18n/fi.po
  analytic_tag_dimension/i18n/fr.po
  analytic_tag_dimension/i18n/fr_CH.po
  analytic_tag_dimension/i18n/hr.po
  analytic_tag_dimension/i18n/hr_HR.po
  analytic_tag_dimension/i18n/hu.po
  analytic_tag_dimension/i18n/it.po
  analytic_tag_dimension/i18n/ja.po
  analytic_tag_dimension/i18n/lt.po
  analytic_tag_dimension/i18n/mk.po
  analytic_tag_dimension/i18n/mn.po
  analytic_tag_dimension/i18n/nb.po
  analytic_tag_dimension/i18n/nl.po
  analytic_tag_dimension/i18n/nl_BE.po
  analytic_tag_dimension/i18n/nl_NL.po
  analytic_tag_dimension/i18n/pt.po
  analytic_tag_dimension/i18n/pt_BR.po
  analytic_tag_dimension/i18n/pt_PT.po
  analytic_tag_dimension/i18n/ro.po
  analytic_tag_dimension/i18n/ru.po
  analytic_tag_dimension/i18n/sl.po
  analytic_tag_dimension/i18n/sv.po
  analytic_tag_dimension/i18n/tr.po
  analytic_tag_dimension/i18n/tr_TR.po
  analytic_tag_dimension/i18n/zh_CN.po
  analytic_tag_dimension/i18n/zh_TW.po
  analytic_tag_dimension/models/__init__.py
  analytic_tag_dimension/models/account_analytic_dimension.py
  analytic_tag_dimension/models/account_analytic_line.py
  analytic_tag_dimension/models/account_analytic_tag.py
  analytic_tag_dimension/models/account_move_line.py
  analytic_tag_dimension/models/analytic.py
  analytic_tag_dimension/models/analytic_dimension_line.py
  analytic_tag_dimension/static/description/index.html
  analytic_tag_dimension/tests/test_analytic_dimension.py
Labels: 13.0.project_te_576

#314 Syncing from upstream OCA/account-analytic (12.0)
  mrp_analytic/i18n/sl.po
Labels: 12.0

#315 Syncing from upstream OCA/account-analytic (12.0)
  account_analytic_distribution_required/i18n/de.po
  account_analytic_distribution_required/i18n/es.po
  account_analytic_distribution_required/i18n/pt.po
  account_analytic_required/i18n/ar.po
  account_analytic_required/i18n/ca.po
  account_analytic_required/i18n/de.po
  account_analytic_required/i18n/es.po
  account_analytic_required/i18n/es_CO.po
  account_analytic_required/i18n/fr.po
  account_analytic_required/i18n/hr_HR.po
  account_analytic_required/i18n/pt.po
  account_analytic_required/i18n/zh_CN.po
  analytic_tag_dimension/i18n/ar.po
  analytic_tag_dimension/i18n/ca.po
  analytic_tag_dimension/i18n/es.po
  analytic_tag_dimension/i18n/es_CO.po
  analytic_tag_dimension/i18n/es_MX.po
  analytic_tag_dimension/i18n/fi.po
  analytic_tag_dimension/i18n/fr.po
  analytic_tag_dimension/i18n/hr.po
  analytic_tag_dimension/i18n/hr_HR.po
  analytic_tag_dimension/i18n/nl.po
  analytic_tag_dimension/i18n/nl_NL.po
  analytic_tag_dimension/i18n/pt.po
Labels: 12.0

#317 Syncing from upstream OCA/account-analytic (12.0)
  account_analytic_distribution_required/i18n/fr.po
Labels: 12.0

#318 Syncing from upstream OCA/account-analytic (13.0)
  .travis.yml
  stock_inventory_analytic/i18n/pt.po
Labels: 13.0
