Repository brain-tec/account-analytic, pull requests merged in 2021-12, with the labels that each got.

#391 Syncing from upstream OCA/account-analytic (13.0)
  oca_dependencies.txt
  purchase_request_analytic/README.rst
  purchase_request_analytic/__init__.py
  purchase_request_analytic/__manifest__.py
  purchase_request_analytic/i18n/purchase_request_analytic.pot
  purchase_request_analytic/models/__init__.py
  purchase_request_analytic/models/purchase_request.py
  purchase_request_analytic/readme/CONTRIBUTORS.rst
  purchase_request_analytic/readme/DESCRIPTION.rst
  purchase_request_analytic/readme/HISTORY.rst
  purchase_request_analytic/readme/USAGE.rst
  purchase_request_analytic/static/description/icon.png
  purchase_request_analytic/static/description/index.html
  purchase_request_analytic/tests/__init__.py
  purchase_request_analytic/tests/test_purchase_request_analytic.py
  purchase_request_analytic/views/purchase_request_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_request_analytic/odoo/addons/purchase_request_analytic
  setup/purchase_request_analytic/setup.py
Labels: 13.0

#392 Syncing from upstream OCA/account-analytic (14.0)
  account_analytic_wip/i18n/fr.po
  account_analytic_wip/i18n/fr_FR.po
  analytic_activity_based_cost/i18n/fr.po
  analytic_activity_based_cost/i18n/fr_FR.po
Labels: 14.0

#395 Merging 13.0 into 13.0.project_MI_465
  oca_dependencies.txt
  purchase_request_analytic/README.rst
  purchase_request_analytic/__init__.py
  purchase_request_analytic/__manifest__.py
  purchase_request_analytic/i18n/purchase_request_analytic.pot
  purchase_request_analytic/models/__init__.py
  purchase_request_analytic/models/purchase_request.py
  purchase_request_analytic/readme/CONTRIBUTORS.rst
  purchase_request_analytic/readme/DESCRIPTION.rst
  purchase_request_analytic/readme/HISTORY.rst
  purchase_request_analytic/readme/USAGE.rst
  purchase_request_analytic/static/description/icon.png
  purchase_request_analytic/static/description/index.html
  purchase_request_analytic/tests/__init__.py
  purchase_request_analytic/tests/test_purchase_request_analytic.py
  purchase_request_analytic/views/purchase_request_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_request_analytic/odoo/addons/purchase_request_analytic
  setup/purchase_request_analytic/setup.py
Labels: 13.0.project_mi_465

#396 Precommit hook fixes
  account_analytic_required/i18n/zh_CN.po
  account_analytic_required/models/account.py
  setup/account_analytic_required/odoo/addons/account_analytic_required
  setup/account_analytic_required/setup.py
Labels: 15.0.t126096

#393 [t126096][MIG] Migration of account_analytic_required
  account_analytic_required/README.rst
  account_analytic_required/__init__.py
  account_analytic_required/__manifest__.py
  account_analytic_required/i18n/account_analytic_required.pot
  account_analytic_required/i18n/ar.po
  account_analytic_required/i18n/ca.po
  account_analytic_required/i18n/de.po
  account_analytic_required/i18n/es.po
  account_analytic_required/i18n/es_CO.po
  account_analytic_required/i18n/fr.po
  account_analytic_required/i18n/hr_HR.po
  account_analytic_required/i18n/nl.po
  account_analytic_required/i18n/pt_BR.po
  account_analytic_required/i18n/zh_CN.po
  account_analytic_required/models/__init__.py
  account_analytic_required/models/account.py
  account_analytic_required/readme/CONFIGURE.rst
  account_analytic_required/readme/CONTRIBUTORS.rst
  account_analytic_required/readme/DESCRIPTION.rst
  account_analytic_required/readme/USAGE.rst
  account_analytic_required/static/description/icon.png
  account_analytic_required/static/description/index.html
  account_analytic_required/tests/__init__.py
  account_analytic_required/tests/test_account_analytic_required.py
  account_analytic_required/views/account_account_type.xml
  setup/account_analytic_required/odoo/addons/account_analytic_required
  setup/account_analytic_required/setup.py
Labels: 15.0.project_mi_465

#397 Syncing from upstream OCA/account-analytic (13.0)
  pos_analytic_by_config/__manifest__.py
  pos_analytic_by_config/models/pos_session.py
Labels: 13.0

#398 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  pos_analytic_by_config/README.rst
  pos_analytic_by_config/__init__.py
  pos_analytic_by_config/__manifest__.py
  pos_analytic_by_config/i18n/ca.po
  pos_analytic_by_config/i18n/de.po
  pos_analytic_by_config/i18n/el_GR.po
  pos_analytic_by_config/i18n/en.po
  pos_analytic_by_config/i18n/es.po
  pos_analytic_by_config/i18n/es_MX.po
  pos_analytic_by_config/i18n/fi.po
  pos_analytic_by_config/i18n/fr.po
  pos_analytic_by_config/i18n/pos_analytic_by_config.pot
  pos_analytic_by_config/i18n/pt_BR.po
  pos_analytic_by_config/i18n/sk_SK.po
  pos_analytic_by_config/i18n/sl.po
  pos_analytic_by_config/i18n/zh_CN.po
  pos_analytic_by_config/models/__init__.py
  pos_analytic_by_config/models/account_move_line.py
  pos_analytic_by_config/models/pos_config.py
  pos_analytic_by_config/models/pos_order.py
  pos_analytic_by_config/models/pos_session.py
  pos_analytic_by_config/readme/CONTRIBUTORS.rst
  pos_analytic_by_config/readme/DESCRIPTION.rst
  pos_analytic_by_config/readme/ROADMAP.rst
  pos_analytic_by_config/readme/USAGE.rst
  pos_analytic_by_config/static/description/icon.png
  pos_analytic_by_config/static/description/index.html
  pos_analytic_by_config/tests/__init__.py
  pos_analytic_by_config/tests/test_pos_analytic_by_config.py
  pos_analytic_by_config/views/pos_config_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/pos_analytic_by_config/odoo/addons/pos_analytic_by_config
  setup/pos_analytic_by_config/setup.py
Labels: 14.0

#400 Syncing from upstream OCA/account-analytic (12.0)
  account_analytic_distribution_required/i18n/ca.po
  stock_inventory_analytic/i18n/es.po
Labels: 12.0
