Repository brain-tec/account-analytic, pull requests merged in 2021-09, with the labels that each got.

#365 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  account_analytic_wip/i18n/account_analytic_wip.pot
  analytic_activity_based_cost/README.rst
  analytic_activity_based_cost/__init__.py
  analytic_activity_based_cost/__manifest__.py
  analytic_activity_based_cost/demo/product_demo.xml
  analytic_activity_based_cost/i18n/analytic_activity_based_cost.pot
  analytic_activity_based_cost/models/__init__.py
  analytic_activity_based_cost/models/account_analytic_line.py
  analytic_activity_based_cost/models/activity_cost_rule.py
  analytic_activity_based_cost/models/product_template.py
  analytic_activity_based_cost/readme/CONFIGURATION.rst
  analytic_activity_based_cost/readme/DESCRIPTION.rst
  analytic_activity_based_cost/readme/USAGE.rst
  analytic_activity_based_cost/security/ir.model.access.csv
  analytic_activity_based_cost/static/description/index.html
  analytic_activity_based_cost/views/account_analytic_line.xml
  analytic_activity_based_cost/views/activity_cost_rule_views.xml
  analytic_activity_based_cost/views/product_template.xml
Labels: 14.0

#366 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  account_analytic_wip/i18n/account_analytic_wip.pot
  analytic_activity_based_cost/__manifest__.py
  analytic_activity_based_cost/demo/product_demo.xml
  analytic_activity_based_cost/i18n/analytic_activity_based_cost.pot
  analytic_activity_based_cost/models/__init__.py
  analytic_activity_based_cost/models/product.py
  analytic_activity_based_cost/views/product.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_analytic/odoo/addons/stock_analytic
  setup/stock_analytic/setup.py
  stock_analytic/README.rst
  stock_analytic/__init__.py
  stock_analytic/__manifest__.py
  stock_analytic/i18n/ca.po
  stock_analytic/i18n/cs_CZ.po
  stock_analytic/i18n/de.po
  stock_analytic/i18n/el_GR.po
  stock_analytic/i18n/es.po
  stock_analytic/i18n/es_EC.po
  stock_analytic/i18n/es_MX.po
  stock_analytic/i18n/fi.po
  stock_analytic/i18n/fr.po
  stock_analytic/i18n/gl.po
  stock_analytic/i18n/gu_IN.po
  stock_analytic/i18n/hi_IN.po
  stock_analytic/i18n/hr.po
  stock_analytic/i18n/hr_HR.po
  stock_analytic/i18n/hu.po
  stock_analytic/i18n/it.po
  stock_analytic/i18n/nl.po
  stock_analytic/i18n/pt.po
  stock_analytic/i18n/pt_BR.po
  stock_analytic/i18n/pt_PT.po
  stock_analytic/i18n/ro.po
  stock_analytic/i18n/sk_SK.po
  stock_analytic/i18n/sl.po
  stock_analytic/i18n/stock_analytic.pot
  stock_analytic/i18n/tr.po
  stock_analytic/i18n/tr_TR.po
  stock_analytic/i18n/vi_VN.po
  stock_analytic/i18n/zh_CN.po
  stock_analytic/models/__init__.py
  stock_analytic/models/product_product.py
  stock_analytic/models/stock.py
  stock_analytic/models/stock_scrap.py
  stock_analytic/readme/CONTRIBUTORS.rst
  stock_analytic/readme/DESCRIPTION.rst
  stock_analytic/readme/USAGE.rst
  stock_analytic/static/description/icon.png
  stock_analytic/static/description/index.html
  stock_analytic/tests/__init__.py
  stock_analytic/tests/test_stock_picking.py
  stock_analytic/tests/test_stock_scrap.py
  stock_analytic/views/stock_move_views.xml
  stock_analytic/views/stock_scrap.xml
Labels: 14.0

#367 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  account_analytic_wip/README.rst
  account_analytic_wip/__manifest__.py
  account_analytic_wip/demo/product_demo.xml
  account_analytic_wip/i18n/account_analytic_wip.pot
  account_analytic_wip/models/__init__.py
  account_analytic_wip/models/account_analytic.py
  account_analytic_wip/models/account_analytic_line.py
  account_analytic_wip/models/account_analytic_tracked.py
  account_analytic_wip/models/account_analytic_tracking.py
  account_analytic_wip/models/account_move.py
  account_analytic_wip/models/activity_cost_rule.py
  account_analytic_wip/models/product_template.py
  account_analytic_wip/readme/CONFIGURATION.rst
  account_analytic_wip/readme/DESCRIPTION.rst
  account_analytic_wip/readme/USAGE.rst
  account_analytic_wip/security/ir.model.access.csv
  account_analytic_wip/static/description/index.html
  account_analytic_wip/tests/test_analytic.py
  account_analytic_wip/views/account_analytic_line.xml
  account_analytic_wip/views/account_analytic_tracking.xml
  account_analytic_wip/views/activity_cost_rule_views.xml
  account_analytic_wip/views/product_template.xml
  analytic_activity_based_cost/i18n/analytic_activity_based_cost.pot
Labels: 14.0

#368 [bt#15853] Bugfix in stock_analytic
  stock_analytic/models/account_analytic_line.py
Labels: bug, 13.0.project_mi_465

#369 Syncing from upstream OCA/account-analytic (10.0)
  account_analytic_default_account/i18n/tr.po
Labels: 10.0
