Repository brain-tec/account-analytic, pull requests merged in 2022-07, with the labels that each got.

#465 [15.0][MIG] analytic_base_department: Migration to 15.0
  analytic_base_department/README.rst
  analytic_base_department/__init__.py
  analytic_base_department/__manifest__.py
  analytic_base_department/i18n/analytic_base_department.pot
  analytic_base_department/i18n/ca.po
  analytic_base_department/i18n/de.po
  analytic_base_department/i18n/el_GR.po
  analytic_base_department/i18n/es.po
  analytic_base_department/i18n/es_CO.po
  analytic_base_department/i18n/es_MX.po
  analytic_base_department/i18n/fi.po
  analytic_base_department/i18n/fr.po
  analytic_base_department/i18n/gu_IN.po
  analytic_base_department/i18n/hi_IN.po
  analytic_base_department/i18n/hr_HR.po
  analytic_base_department/i18n/nl.po
  analytic_base_department/i18n/pt.po
  analytic_base_department/i18n/pt_BR.po
  analytic_base_department/i18n/sk_SK.po
  analytic_base_department/i18n/sl.po
  analytic_base_department/i18n/zh_CN.po
  analytic_base_department/models/__init__.py
  analytic_base_department/models/analytic.py
  analytic_base_department/models/hr_department.py
  analytic_base_department/readme/CONTRIBUTORS.rst
  analytic_base_department/readme/DESCRIPTION.rst
  analytic_base_department/readme/HISTORY.rst
  analytic_base_department/static/description/icon.png
  analytic_base_department/static/description/index.html
  analytic_base_department/tests/__init__.py
  analytic_base_department/tests/test_line_department.py
  analytic_base_department/views/analytic.xml
  analytic_base_department/views/hr_department_views.xml
  setup/analytic_base_department/odoo/addons/analytic_base_department
  setup/analytic_base_department/setup.py
Labels: 15.0.project_me_652

#466 [t130465]15.0 mig mrp analytic
  mrp_analytic/README.rst
  mrp_analytic/__init__.py
  mrp_analytic/__manifest__.py
  mrp_analytic/i18n/ca.po
  mrp_analytic/i18n/de.po
  mrp_analytic/i18n/el_GR.po
  mrp_analytic/i18n/es.po
  mrp_analytic/i18n/es_MX.po
  mrp_analytic/i18n/fi.po
  mrp_analytic/i18n/fr.po
  mrp_analytic/i18n/hr.po
  mrp_analytic/i18n/mrp_analytic.pot
  mrp_analytic/i18n/pt_BR.po
  mrp_analytic/i18n/sk_SK.po
  mrp_analytic/i18n/sl.po
  mrp_analytic/i18n/tr.po
  mrp_analytic/i18n/zh_CN.po
  mrp_analytic/models/__init__.py
  mrp_analytic/models/analytic_account.py
  mrp_analytic/models/stock_move.py
  mrp_analytic/readme/CONTRIBUTORS.rst
  mrp_analytic/readme/DESCRIPTION.rst
  mrp_analytic/readme/HISTORY.rst
  mrp_analytic/readme/USAGE.rst
  mrp_analytic/static/description/icon.png
  mrp_analytic/static/description/icon.svg
  mrp_analytic/static/description/index.html
  mrp_analytic/tests/__init__.py
  mrp_analytic/tests/test_mrp_analytic.py
  mrp_analytic/views/analytic_account_view.xml
  mrp_analytic/views/mrp_view.xml
Labels: 15.0.project_mi_465.t130465

#467 [t130465] MIDE DEV V15 Migration - Misc - Part 2 (OCA & BT)
  mrp_analytic/README.rst
  mrp_analytic/__init__.py
  mrp_analytic/__manifest__.py
  mrp_analytic/i18n/ca.po
  mrp_analytic/i18n/de.po
  mrp_analytic/i18n/el_GR.po
  mrp_analytic/i18n/es.po
  mrp_analytic/i18n/es_MX.po
  mrp_analytic/i18n/fi.po
  mrp_analytic/i18n/fr.po
  mrp_analytic/i18n/hr.po
  mrp_analytic/i18n/mrp_analytic.pot
  mrp_analytic/i18n/pt_BR.po
  mrp_analytic/i18n/sk_SK.po
  mrp_analytic/i18n/sl.po
  mrp_analytic/i18n/tr.po
  mrp_analytic/i18n/zh_CN.po
  mrp_analytic/models/__init__.py
  mrp_analytic/models/analytic_account.py
  mrp_analytic/models/stock_move.py
  mrp_analytic/readme/CONTRIBUTORS.rst
  mrp_analytic/readme/DESCRIPTION.rst
  mrp_analytic/readme/HISTORY.rst
  mrp_analytic/readme/USAGE.rst
  mrp_analytic/static/description/icon.png
  mrp_analytic/static/description/icon.svg
  mrp_analytic/static/description/index.html
  mrp_analytic/tests/__init__.py
  mrp_analytic/tests/test_mrp_analytic.py
  mrp_analytic/views/analytic_account_view.xml
  mrp_analytic/views/mrp_view.xml
Labels: 15.0.project_mi_465
