Repository brain-tec/account-analytic, pull requests merged in 2022-06, with the labels that each got.

#460 Updating from latest OCA 13.0
  purchase_analytic/i18n/es.po
Labels: 13.0.project_mi_465

#461 Syncing from upstream OCA/account-analytic (14.0)
  account_analytic_parent/i18n/fr.po
Labels: 14.0

#462 Syncing from upstream OCA/account-analytic (15.0)
  account_analytic_parent/i18n/fr.po
Labels: 15.0

#463 Backmerging 15.0 into 15.0.project_MI_465
  account_analytic_parent/i18n/fr.po
Labels: 15.0.project_mi_465
