Repository brain-tec/account-analytic, pull requests merged in 2022-03, with the labels that each got.

#426 Updating from latest OCA 13.0
  account_analytic_required/README.rst
  account_analytic_required/__manifest__.py
  account_analytic_required/i18n/pt_BR.po
  account_analytic_required/models/account.py
  account_analytic_required/readme/CONTRIBUTORS.rst
  account_analytic_required/static/description/index.html
  account_analytic_required/tests/test_account_analytic_required.py
  stock_inventory_analytic/i18n/es.po
Labels: 13.0.project_mi_465

#427 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  account_analytic_required/README.rst
  account_analytic_required/__manifest__.py
  account_analytic_required/models/account.py
  account_analytic_required/readme/CONTRIBUTORS.rst
  account_analytic_required/static/description/index.html
  account_analytic_required/tests/test_account_analytic_required.py
  analytic_activity_based_cost/i18n/analytic_activity_based_cost.pot
  analytic_activity_based_cost/i18n/fr.po
  analytic_activity_based_cost/i18n/fr_FR.po
Labels: 14.0

#428 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  account_analytic_required/__manifest__.py
  account_analytic_required/tests/test_account_analytic_required.py
Labels: 14.0

#429 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  sale_stock_analytic/README.rst
  sale_stock_analytic/__init__.py
  sale_stock_analytic/__manifest__.py
  sale_stock_analytic/i18n/sale_stock_analytic.pot
  sale_stock_analytic/models/__init__.py
  sale_stock_analytic/models/stock_rule.py
  sale_stock_analytic/static/description/icon.png
  sale_stock_analytic/tests/__init__.py
  sale_stock_analytic/tests/test_sale_stock_analytic.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_stock_analytic/odoo/addons/sale_stock_analytic
  setup/sale_stock_analytic/setup.py
  stock_inventory_analytic/__manifest__.py
  stock_inventory_analytic/models/stock_inventory_line.py
Labels: 14.0

#431 Syncing from upstream OCA/account-analytic (12.0)
  account_analytic_required/i18n/ca.po
  account_analytic_sequence/i18n/ca.po
  analytic_tag_dimension/i18n/ca.po
  stock_analytic/i18n/ca.po
Labels: 12.0

#432 Syncing from upstream OCA/account-analytic (13.0)
  account_analytic_required/i18n/ca.po
  account_analytic_sequence/i18n/ca.po
  analytic_base_department/i18n/ca.po
  analytic_tag_dimension/i18n/ca.po
  pos_analytic_by_config/i18n/ca.po
Labels: 13.0

#433 Syncing from upstream OCA/account-analytic (14.0)
  mrp_analytic/i18n/ca.po
  pos_analytic_by_config/i18n/ca.po
  stock_analytic/i18n/ca.po
Labels: 14.0

#434 Syncing from upstream OCA/account-analytic (9.0)
  account_analytic_no_lines/i18n/ca.po
  account_analytic_parent/i18n/ca.po
  account_analytic_required/i18n/ca.po
  analytic_base_department/i18n/ca.po
  procurement_analytic/i18n/ca.po
  stock_analytic/i18n/ca.po
Labels: 9.0

#439 Create test-requirements for account_menu
  test-requirements.txt
Labels: 15.0.project_mi_465

#440 Syncing from upstream OCA/account-analytic (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  account_analytic_required/models/account.py
  analytic_tag_dimension_enhanced/models/account_analytic_tag.py
  procurement_mto_analytic/tests/test_purchase_procurement_analytic.py
Labels: 14.0

#441 Syncing from upstream OCA/account-analytic (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: 15.0
