Repository brain-tec/account-analytic, pull requests merged in 2022-01, with the labels that each got.

#401 [t126096] Readded dependecy to account_menu
  account_analytic_required/__manifest__.py
Labels: 15.0.project_mi_465

#402 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  mrp_analytic_child_mo/__manifest__.py
  mrp_analytic_child_mo/models/mrp_production.py
Labels: 14.0

#403 Syncing from upstream OCA/account-analytic (12.0)
  mrp_analytic/i18n/ca.po
  mrp_analytic/i18n/es.po
Labels: 12.0

#404 Syncing from upstream OCA/account-analytic (14.0)
  account_analytic_required/i18n/ca.po
  account_analytic_required/i18n/es.po
  account_analytic_sequence/i18n/ca.po
  account_analytic_sequence/i18n/es.po
  analytic_tag_dimension/i18n/ca.po
  analytic_tag_dimension/i18n/es.po
Labels: 14.0

#405 Merging 13.0 into 13.0.project_MI_465
  pos_analytic_by_config/__manifest__.py
  pos_analytic_by_config/models/pos_session.py
Labels: 13.0.project_mi_465

#406 Syncing from upstream OCA/account-analytic (13.0)
  .travis.yml
  account_analytic_parent/__manifest__.py
  account_analytic_parent/tests/test_account_analytic_account.py
Labels: 13.0

#407 Syncing from upstream OCA/account-analytic (14.0)
  .travis.yml
  README.md
  account_analytic_parent/__manifest__.py
  account_analytic_parent/tests/test_account_analytic_account.py
Labels: 14.0

#409 Syncing from upstream OCA/account-analytic (14.0)
  account_analytic_required/i18n/sv.po
Labels: 14.0

#412 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  account_analytic_required/__manifest__.py
  account_analytic_required/i18n/fr.po
Labels: 14.0
