Repository brain-tec/account-analytic, pull requests merged in 2022-08, with the labels that each got.

#471 Syncing from upstream OCA/account-analytic (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_analytic_parent/__manifest__.py
  account_analytic_sequence/README.rst
  account_analytic_sequence/__manifest__.py
  account_analytic_sequence/readme/CONTRIBUTORS.rst
  account_analytic_sequence/static/description/index.html
  account_analytic_tag_default/__manifest__.py
  analytic_partner/__manifest__.py
  procurement_mto_analytic/__manifest__.py
  procurement_mto_analytic/models/stock_rule.py
  purchase_stock_analytic/README.rst
  purchase_stock_analytic/__init__.py
  purchase_stock_analytic/__manifest__.py
  purchase_stock_analytic/i18n/purchase_stock_analytic.pot
  purchase_stock_analytic/models/__init__.py
  purchase_stock_analytic/models/purchase_order_line.py
  purchase_stock_analytic/static/description/icon.png
  purchase_stock_analytic/tests/__init__.py
  purchase_stock_analytic/tests/test_purchase_stock_analytic.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_stock_analytic/.eggs/README.txt
  setup/purchase_stock_analytic/odoo/addons/purchase_stock_analytic
  setup/purchase_stock_analytic/setup.py
  stock_inventory_analytic/__manifest__.py
Labels: 13.0

#472 Syncing from upstream OCA/account-analytic (15.0)
  README.md
  account_analytic_required/README.rst
  account_analytic_required/__init__.py
  account_analytic_required/__manifest__.py
  account_analytic_required/i18n/account_analytic_required.pot
  account_analytic_required/i18n/ar.po
  account_analytic_required/i18n/ca.po
  account_analytic_required/i18n/de.po
  account_analytic_required/i18n/es.po
  account_analytic_required/i18n/es_CO.po
  account_analytic_required/i18n/fr.po
  account_analytic_required/i18n/hr_HR.po
  account_analytic_required/i18n/nl.po
  account_analytic_required/i18n/pt_BR.po
  account_analytic_required/i18n/sv.po
  account_analytic_required/i18n/zh_CN.po
  account_analytic_required/models/__init__.py
  account_analytic_required/models/account.py
  account_analytic_required/readme/CONFIGURE.rst
  account_analytic_required/readme/CONTRIBUTORS.rst
  account_analytic_required/readme/DESCRIPTION.rst
  account_analytic_required/readme/USAGE.rst
  account_analytic_required/static/description/icon.png
  account_analytic_required/static/description/index.html
  account_analytic_required/tests/__init__.py
  account_analytic_required/tests/test_account_analytic_required.py
  account_analytic_required/views/account_account_type.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_analytic_required/odoo/addons/account_analytic_required
  setup/account_analytic_required/setup.py
Labels: 15.0

#476 [FIX] Conflict solving with 13.0 (travis.yml removed)
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_analytic_parent/__manifest__.py
  account_analytic_sequence/README.rst
  account_analytic_sequence/__manifest__.py
  account_analytic_sequence/readme/CONTRIBUTORS.rst
  account_analytic_sequence/static/description/index.html
  account_analytic_tag_default/__manifest__.py
  analytic_partner/__manifest__.py
  procurement_mto_analytic/__manifest__.py
  procurement_mto_analytic/models/stock_rule.py
  purchase_stock_analytic/README.rst
  purchase_stock_analytic/__init__.py
  purchase_stock_analytic/__manifest__.py
  purchase_stock_analytic/i18n/purchase_stock_analytic.pot
  purchase_stock_analytic/models/__init__.py
  purchase_stock_analytic/models/purchase_order_line.py
  purchase_stock_analytic/static/description/icon.png
  purchase_stock_analytic/tests/__init__.py
  purchase_stock_analytic/tests/test_purchase_stock_analytic.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_stock_analytic/.eggs/README.txt
  setup/purchase_stock_analytic/odoo/addons/purchase_stock_analytic
  setup/purchase_stock_analytic/setup.py
  stock_inventory_analytic/__manifest__.py
Labels: 13.0.project_mi_465

#477 Syncing from upstream OCA/account-analytic (13.0)
  README.md
  purchase_analytic/README.rst
  purchase_analytic/__manifest__.py
  purchase_analytic/i18n/es.po
  purchase_analytic/i18n/fr.po
  purchase_analytic/i18n/purchase_analytic.pot
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/static/description/index.html
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
Labels: 13.0

#479 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  account_analytic_sequence/i18n/hr.po
  purchase_analytic/README.rst
  purchase_analytic/__manifest__.py
  purchase_analytic/i18n/es.po
  purchase_analytic/i18n/fr.po
  purchase_analytic/i18n/purchase_analytic.pot
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/static/description/index.html
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
Labels: 14.0

#480 Syncing from upstream OCA/account-analytic (15.0)
  README.md
  purchase_analytic/README.rst
  purchase_analytic/__manifest__.py
  purchase_analytic/i18n/es.po
  purchase_analytic/i18n/fr.po
  purchase_analytic/i18n/purchase_analytic.pot
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/static/description/index.html
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
Labels: 15.0

#482 [FIX] Pre-commit applied
  setup/mrp_analytic/odoo/addons/mrp_analytic
  setup/mrp_analytic/setup.py
Labels: 15.0.project_mi_465

#481 Backmerging 15.0 into 15.0.project_MI_465
  README.md
  purchase_analytic/README.rst
  purchase_analytic/__manifest__.py
  purchase_analytic/i18n/es.po
  purchase_analytic/i18n/fr.po
  purchase_analytic/i18n/purchase_analytic.pot
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/static/description/index.html
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
Labels: 15.0.project_mi_465

#483 Backmerging 13.0 into 13.0.project_MI_465
  README.md
  purchase_analytic/README.rst
  purchase_analytic/__manifest__.py
  purchase_analytic/i18n/es.po
  purchase_analytic/i18n/fr.po
  purchase_analytic/i18n/purchase_analytic.pot
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/static/description/index.html
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
Labels: 13.0.project_mi_465
