Repository brain-tec/account-analytic, pull requests merged in 2022-05, with the labels that each got.

#449 Updating from latest OCA 15.0
  README.md
  account_analytic_sequence/README.rst
  account_analytic_sequence/__init__.py
  account_analytic_sequence/__manifest__.py
  account_analytic_sequence/data/sequence.xml
  account_analytic_sequence/hooks.py
  account_analytic_sequence/i18n/account_analytic_sequence.pot
  account_analytic_sequence/i18n/ca.po
  account_analytic_sequence/i18n/cs_CZ.po
  account_analytic_sequence/i18n/de.po
  account_analytic_sequence/i18n/el_GR.po
  account_analytic_sequence/i18n/es.po
  account_analytic_sequence/i18n/es_EC.po
  account_analytic_sequence/i18n/es_MX.po
  account_analytic_sequence/i18n/fi.po
  account_analytic_sequence/i18n/fr.po
  account_analytic_sequence/i18n/gl.po
  account_analytic_sequence/i18n/gu_IN.po
  account_analytic_sequence/i18n/hi_IN.po
  account_analytic_sequence/i18n/hr.po
  account_analytic_sequence/i18n/hr_HR.po
  account_analytic_sequence/i18n/it.po
  account_analytic_sequence/i18n/nl.po
  account_analytic_sequence/i18n/pt.po
  account_analytic_sequence/i18n/pt_BR.po
  account_analytic_sequence/i18n/sk_SK.po
  account_analytic_sequence/i18n/sl.po
  account_analytic_sequence/i18n/zh_CN.po
  account_analytic_sequence/models/__init__.py
  account_analytic_sequence/models/account_analytic_account.py
  account_analytic_sequence/readme/CONTRIBUTORS.rst
  account_analytic_sequence/readme/DESCRIPTION.rst
  account_analytic_sequence/readme/USAGE.rst
  account_analytic_sequence/static/description/icon.png
  account_analytic_sequence/static/description/index.html
  account_analytic_sequence/tests/__init__.py
  account_analytic_sequence/tests/test_analytic_sequence.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_analytic_sequence/odoo/addons/account_analytic_sequence
  setup/account_analytic_sequence/setup.py
Labels: 15.0.project_mi_465

#450 Syncing from upstream OCA/account-analytic (14.0)
  .copier-answers.yml
  .github/workflows/test.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  product_analytic_purchase/README.rst
  product_analytic_purchase/__init__.py
  product_analytic_purchase/__manifest__.py
  product_analytic_purchase/i18n/ca.po
  product_analytic_purchase/i18n/cs_CZ.po
  product_analytic_purchase/i18n/es.po
  product_analytic_purchase/i18n/fr.po
  product_analytic_purchase/i18n/hr.po
  product_analytic_purchase/i18n/product_analytic_purchase.pot
  product_analytic_purchase/models/__init__.py
  product_analytic_purchase/models/purchase_order_line.py
  product_analytic_purchase/static/description/icon.png
  product_analytic_purchase/tests/__init__.py
  product_analytic_purchase/tests/test_purchase.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_analytic_purchase/odoo/addons/product_analytic_purchase
  setup/product_analytic_purchase/setup.py
Labels: 14.0

#451 Syncing from upstream OCA/account-analytic (15.0)
  README.md
  purchase_analytic/README.rst
  purchase_analytic/__init__.py
  purchase_analytic/__manifest__.py
  purchase_analytic/i18n/es.po
  purchase_analytic/i18n/fr.po
  purchase_analytic/i18n/purchase_analytic.pot
  purchase_analytic/models/__init__.py
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/readme/DESCRIPTION.rst
  purchase_analytic/readme/HISTORY.rst
  purchase_analytic/static/description/icon.png
  purchase_analytic/static/description/index.html
  purchase_analytic/tests/__init__.py
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_analytic/odoo/addons/purchase_analytic
  setup/purchase_analytic/setup.py
Labels: 15.0

#452 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  account_analytic_wip/__manifest__.py
  account_analytic_wip/data/ir_config_parameter_data.xml
  account_analytic_wip/demo/product_demo.xml
  account_analytic_wip/i18n/account_analytic_wip.pot
  account_analytic_wip/i18n/fr.po
  account_analytic_wip/i18n/fr_FR.po
  account_analytic_wip/i18n/sv.po
  account_analytic_wip/models/__init__.py
  account_analytic_wip/models/account_analytic_line.py
  account_analytic_wip/models/account_analytic_tracking.py
  account_analytic_wip/models/account_move.py
  account_analytic_wip/models/product_category.py
  account_analytic_wip/models/product_template.py
  account_analytic_wip/tests/test_analytic.py
  account_analytic_wip/views/account_analytic_tracking.xml
  account_analytic_wip/views/product_category.xml
  account_analytic_wip/views/product_category_view.xml
  analytic_activity_based_cost/__manifest__.py
  analytic_activity_based_cost/models/account_analytic_line.py
  stock_analytic/__manifest__.py
  stock_analytic/models/stock.py
Labels: 14.0

#454 Merging 15.0 into 15.0.project_MI_465
  README.md
  purchase_analytic/README.rst
  purchase_analytic/__init__.py
  purchase_analytic/__manifest__.py
  purchase_analytic/i18n/es.po
  purchase_analytic/i18n/fr.po
  purchase_analytic/i18n/purchase_analytic.pot
  purchase_analytic/models/__init__.py
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/readme/DESCRIPTION.rst
  purchase_analytic/readme/HISTORY.rst
  purchase_analytic/static/description/icon.png
  purchase_analytic/static/description/index.html
  purchase_analytic/tests/__init__.py
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_analytic/odoo/addons/purchase_analytic
  setup/purchase_analytic/setup.py
Labels: 15.0.project_mi_465

#456 Syncing from upstream OCA/account-analytic (14.0)
  README.md
  purchase_request_analytic/README.rst
  purchase_request_analytic/__init__.py
  purchase_request_analytic/__manifest__.py
  purchase_request_analytic/i18n/purchase_request_analytic.pot
  purchase_request_analytic/models/__init__.py
  purchase_request_analytic/models/purchase_request.py
  purchase_request_analytic/readme/CONTRIBUTORS.rst
  purchase_request_analytic/readme/DESCRIPTION.rst
  purchase_request_analytic/readme/HISTORY.rst
  purchase_request_analytic/readme/USAGE.rst
  purchase_request_analytic/static/description/icon.png
  purchase_request_analytic/static/description/index.html
  purchase_request_analytic/tests/__init__.py
  purchase_request_analytic/tests/test_purchase_request_analytic.py
  purchase_request_analytic/views/purchase_request_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/purchase_request_analytic/odoo/addons/purchase_request_analytic
  setup/purchase_request_analytic/setup.py
Labels: 14.0

#457 Added swig to apt packages
  .travis.yml
Labels: 13.0.project_mi_465

#458 Syncing from upstream OCA/account-analytic (13.0)
  purchase_analytic/i18n/es.po
Labels: 13.0
