Repository brain-tec/account-analytic, pull requests merged in 2024-07, with the labels that each got.

#725 Syncing from upstream OCA/account-analytic (13.0)
  account_analytic_parent/i18n/fr.po
Labels: 13.0

#726 Syncing from upstream OCA/account-analytic (17.0)
  account_analytic_parent/i18n/it.po
Labels: 17.0

#727 17.0 mig product analytic
  product_analytic/README.rst
  product_analytic/__init__.py
  product_analytic/__manifest__.py
  product_analytic/demo/product_demo.xml
  product_analytic/i18n/ar.po
  product_analytic/i18n/bs.po
  product_analytic/i18n/ca.po
  product_analytic/i18n/cs.po
  product_analytic/i18n/cs_CZ.po
  product_analytic/i18n/de.po
  product_analytic/i18n/en_GB.po
  product_analytic/i18n/es.po
  product_analytic/i18n/es_CO.po
  product_analytic/i18n/es_CR.po
  product_analytic/i18n/es_EC.po
  product_analytic/i18n/es_MX.po
  product_analytic/i18n/et.po
  product_analytic/i18n/fi.po
  product_analytic/i18n/fr.po
  product_analytic/i18n/fr_CH.po
  product_analytic/i18n/hr.po
  product_analytic/i18n/hr_HR.po
  product_analytic/i18n/hu.po
  product_analytic/i18n/it.po
  product_analytic/i18n/ja.po
  product_analytic/i18n/lt.po
  product_analytic/i18n/mk.po
  product_analytic/i18n/mn.po
  product_analytic/i18n/nb.po
  product_analytic/i18n/nl.po
  product_analytic/i18n/nl_BE.po
  product_analytic/i18n/nl_NL.po
  product_analytic/i18n/product_analytic.pot
  product_analytic/i18n/pt.po
  product_analytic/i18n/pt_BR.po
  product_analytic/i18n/pt_PT.po
  product_analytic/i18n/ro.po
  product_analytic/i18n/ru.po
  product_analytic/i18n/sl.po
  product_analytic/i18n/sv.po
  product_analytic/i18n/tr.po
  product_analytic/i18n/tr_TR.po
  product_analytic/i18n/zh_CN.po
  product_analytic/i18n/zh_TW.po
  product_analytic/models/__init__.py
  product_analytic/models/account_move.py
  product_analytic/models/product.py
  product_analytic/models/product_category.py
  product_analytic/pyproject.toml
  product_analytic/readme/CONTRIBUTORS.md
  product_analytic/readme/DESCRIPTION.md
  product_analytic/readme/HISTORY.md
  product_analytic/readme/USAGE.md
  product_analytic/static/description/icon.png
  product_analytic/static/description/index.html
  product_analytic/tests/__init__.py
  product_analytic/tests/test_account_move.py
  product_analytic/views/product_view.xml
Labels: 17.0.project_bo_543

#728 Syncing from upstream OCA/account-analytic (15.0)
  README.md
  purchase_request_analytic/README.rst
  purchase_request_analytic/__manifest__.py
  purchase_request_analytic/models/purchase_request.py
  purchase_request_analytic/static/description/index.html
  purchase_request_analytic/tests/test_purchase_request_analytic.py
Labels: 15.0

#729 Syncing from upstream OCA/account-analytic (17.0)
  .copier-answers.yml
  .eslintrc.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 17.0

#730 Syncing from upstream OCA/account-analytic (15.0)
  README.md
  account_analytic_parent/README.rst
  account_analytic_parent/__manifest__.py
  account_analytic_parent/models/account_analytic_account.py
  account_analytic_parent/static/description/index.html
Labels: 15.0

#731 [t148259] Get some changes from external repo
  account_analytic_required/README.rst
  account_analytic_required/__init__.py
  account_analytic_required/__manifest__.py
  account_analytic_required/i18n/account_analytic_required.pot
  account_analytic_required/i18n/ar.po
  account_analytic_required/i18n/ca.po
  account_analytic_required/i18n/de.po
  account_analytic_required/i18n/es.po
  account_analytic_required/i18n/es_CO.po
  account_analytic_required/i18n/fr.po
  account_analytic_required/i18n/hr.po
  account_analytic_required/i18n/hr_HR.po
  account_analytic_required/i18n/it.po
  account_analytic_required/i18n/nl.po
  account_analytic_required/i18n/pt_BR.po
  account_analytic_required/i18n/sv.po
  account_analytic_required/i18n/zh_CN.po
  account_analytic_required/models/__init__.py
  account_analytic_required/models/account.py
  account_analytic_required/pyproject.toml
  account_analytic_required/readme/CONFIGURE.md
  account_analytic_required/readme/CONTRIBUTORS.md
  account_analytic_required/readme/CREDITS.md
  account_analytic_required/readme/DESCRIPTION.md
  account_analytic_required/readme/USAGE.md
  account_analytic_required/static/description/icon.png
  account_analytic_required/static/description/index.html
  account_analytic_required/tests/__init__.py
  account_analytic_required/tests/test_account_analytic_required.py
  account_analytic_required/views/account_account_views.xml
Labels: 17.0.project_te_576, 17.0.project_te_576.t148259

#732 [t150462] Migration of account_analytic_required
  account_analytic_required/README.rst
  account_analytic_required/__init__.py
  account_analytic_required/__manifest__.py
  account_analytic_required/i18n/account_analytic_required.pot
  account_analytic_required/i18n/ar.po
  account_analytic_required/i18n/ca.po
  account_analytic_required/i18n/de.po
  account_analytic_required/i18n/es.po
  account_analytic_required/i18n/es_CO.po
  account_analytic_required/i18n/fr.po
  account_analytic_required/i18n/hr.po
  account_analytic_required/i18n/hr_HR.po
  account_analytic_required/i18n/it.po
  account_analytic_required/i18n/nl.po
  account_analytic_required/i18n/pt_BR.po
  account_analytic_required/i18n/sv.po
  account_analytic_required/i18n/zh_CN.po
  account_analytic_required/models/__init__.py
  account_analytic_required/models/account.py
  account_analytic_required/pyproject.toml
  account_analytic_required/readme/CONFIGURE.md
  account_analytic_required/readme/CONTRIBUTORS.md
  account_analytic_required/readme/CREDITS.md
  account_analytic_required/readme/DESCRIPTION.md
  account_analytic_required/readme/USAGE.md
  account_analytic_required/static/description/icon.png
  account_analytic_required/static/description/index.html
  account_analytic_required/tests/__init__.py
  account_analytic_required/tests/test_account_analytic_required.py
  account_analytic_required/views/account_account_views.xml
Labels: 17.0.project_te_576.t150462

#733 [t150462] Migration of account_analytic_required
  account_analytic_required/README.rst
  account_analytic_required/__init__.py
  account_analytic_required/__manifest__.py
  account_analytic_required/i18n/account_analytic_required.pot
  account_analytic_required/i18n/ar.po
  account_analytic_required/i18n/ca.po
  account_analytic_required/i18n/de.po
  account_analytic_required/i18n/es.po
  account_analytic_required/i18n/es_CO.po
  account_analytic_required/i18n/fr.po
  account_analytic_required/i18n/hr.po
  account_analytic_required/i18n/hr_HR.po
  account_analytic_required/i18n/it.po
  account_analytic_required/i18n/nl.po
  account_analytic_required/i18n/pt_BR.po
  account_analytic_required/i18n/sv.po
  account_analytic_required/i18n/zh_CN.po
  account_analytic_required/models/__init__.py
  account_analytic_required/models/account.py
  account_analytic_required/pyproject.toml
  account_analytic_required/readme/CONFIGURE.md
  account_analytic_required/readme/CONTRIBUTORS.md
  account_analytic_required/readme/CREDITS.md
  account_analytic_required/readme/DESCRIPTION.md
  account_analytic_required/readme/USAGE.md
  account_analytic_required/static/description/icon.png
  account_analytic_required/static/description/index.html
  account_analytic_required/tests/__init__.py
  account_analytic_required/tests/test_account_analytic_required.py
  account_analytic_required/views/account_account_views.xml
Labels: 17.0.project_te_576

#734 Syncing from upstream OCA/account-analytic (10.0)
  account_analytic_distribution_required/i18n/fa_IR.po
Labels: 10.0

#735 Syncing from upstream OCA/account-analytic (17.0)
  account_analytic_parent/i18n/it.po
Labels: 17.0

#737 Syncing from upstream OCA/account-analytic (17.0)
  README.md
  account_analytic_required/README.rst
  account_analytic_required/__init__.py
  account_analytic_required/__manifest__.py
  account_analytic_required/i18n/account_analytic_required.pot
  account_analytic_required/i18n/ar.po
  account_analytic_required/i18n/ca.po
  account_analytic_required/i18n/de.po
  account_analytic_required/i18n/es.po
  account_analytic_required/i18n/es_CO.po
  account_analytic_required/i18n/fr.po
  account_analytic_required/i18n/hr.po
  account_analytic_required/i18n/hr_HR.po
  account_analytic_required/i18n/it.po
  account_analytic_required/i18n/nl.po
  account_analytic_required/i18n/pt_BR.po
  account_analytic_required/i18n/sv.po
  account_analytic_required/i18n/zh_CN.po
  account_analytic_required/models/__init__.py
  account_analytic_required/models/account.py
  account_analytic_required/pyproject.toml
  account_analytic_required/readme/CONFIGURE.md
  account_analytic_required/readme/CONTRIBUTORS.md
  account_analytic_required/readme/CREDITS.md
  account_analytic_required/readme/DESCRIPTION.md
  account_analytic_required/readme/USAGE.md
  account_analytic_required/static/description/icon.png
  account_analytic_required/static/description/index.html
  account_analytic_required/tests/__init__.py
  account_analytic_required/tests/test_account_analytic_required.py
  account_analytic_required/views/account_account_views.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0
