Repository brain-tec/account-analytic, pull requests merged in 2024-06, with the labels that each got.

#713 Syncing from upstream OCA/account-analytic (16.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_landed_costs_analytic/odoo/addons/stock_landed_costs_analytic
  setup/stock_landed_costs_analytic/setup.py
  stock_landed_costs_analytic/README.rst
  stock_landed_costs_analytic/__init__.py
  stock_landed_costs_analytic/__manifest__.py
  stock_landed_costs_analytic/i18n/es.po
  stock_landed_costs_analytic/i18n/stock_landed_costs_analytic.pot
  stock_landed_costs_analytic/models/__init__.py
  stock_landed_costs_analytic/models/stock_landed_cost_lines.py
  stock_landed_costs_analytic/models/stock_valuation_adjustment_lines.py
  stock_landed_costs_analytic/static/description/icon.png
  stock_landed_costs_analytic/tests/__init__.py
  stock_landed_costs_analytic/tests/test_stock_landed_costs_analytic.py
  stock_landed_costs_analytic/views/stock_landed_cost_lines.xml
Labels: 16.0

#715 Syncing from upstream OCA/account-analytic (16.0)
  stock_landed_costs_analytic/i18n/it.po
Labels: 16.0

#716 Syncing from upstream OCA/account-analytic (10.0)
  analytic_tag_dimension_purchase_warning/__manifest__.py
  analytic_tag_dimension_sale_warning/__manifest__.py
Labels: 10.0

#717 Syncing from upstream OCA/account-analytic (11.0)
  analytic_tag_dimension_sale_warning/__manifest__.py
Labels: 11.0

#718 Syncing from upstream OCA/account-analytic (13.0)
  analytic_tag_dimension_sale_warning/README.rst
  analytic_tag_dimension_sale_warning/__manifest__.py
  analytic_tag_dimension_sale_warning/static/description/index.html
Labels: 13.0

#719 Syncing from upstream OCA/account-analytic (16.0)
  README.md
  stock_picking_analytic/README.rst
  stock_picking_analytic/__manifest__.py
  stock_picking_analytic/models/stock_picking.py
  stock_picking_analytic/static/description/index.html
  stock_picking_analytic/tests/test_picking_analytic_account.py
Labels: 16.0

#720 Syncing from upstream OCA/account-analytic (16.0)
  stock_landed_costs_analytic/i18n/it.po
Labels: 16.0

#721 Syncing from upstream OCA/account-analytic (17.0)
  account_analytic_parent/i18n/zh_CN.po
  account_analytic_tag/i18n/zh_CN.po
  analytic_base_department/i18n/zh_CN.po
Labels: 17.0

#722 Syncing from upstream OCA/account-analytic (16.0)
  account_analytic_required/i18n/hr.po
  account_analytic_sequence/i18n/hr.po
  product_analytic/i18n/hr.po
  stock_analytic/i18n/hr.po
Labels: 16.0

#723 [BACK] Backmerge
  account_analytic_parent/i18n/zh_CN.po
  account_analytic_tag/i18n/zh_CN.po
  analytic_base_department/i18n/zh_CN.po
Labels: 17.0.project_te_576

#724 Syncing from upstream OCA/account-analytic (16.0)
  account_analytic_parent/i18n/hr.po
Labels: 16.0
